export const DASHBOARD_CACHE = Symbol('DASHBOARD_CACHE');
export const BACKFILL_QUEUE = Symbol('BACKFILL_QUEUE');

export const OVERVIEW_REPOSITORY = Symbol('OVERVIEW_REPOSITORY');
export const PAYMENT_REPOSITORY = Symbol('PAYMENT_REPOSITORY');
export const AGENT_REPOSITORY = Symbol('AGENT_REPOSITORY');
export const SERVICE_CATALOG_REPOSITORY = Symbol('SERVICE_CATALOG_REPOSITORY');
export const EVIDENCE_REPOSITORY = Symbol('EVIDENCE_REPOSITORY');
export const INTERACTION_REPOSITORY = Symbol('INTERACTION_REPOSITORY');
export const STATS_REPOSITORY = Symbol('STATS_REPOSITORY');
export const OPERATIONS_REPOSITORY = Symbol('OPERATIONS_REPOSITORY');
